# Copyright 2023 - Huroos srl - www.huroos.com
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html)

{
    'name': "Huroos | APG23",
    'summary': """Modulo custom per APG23""",
    'description': """Modulo custom per APG23""",

    'author': "Huroos - www.huroos.com",
    'website': "www.huroos.com",
    'category': 'General',
    'license': 'LGPL-3',
    'version': '17.15.1',
    "external_dependencies": {
        "python": [
            "xmltodict",
            "dpath"
        ]
    },

    'depends': [
        'base_setup',
        'mail',
        'stock',
        'account_accountant',
        'l10n_it_account',
        'contacts',
        'huroos_report_bilancio',
        'partner_firstname',
        'huroos_multicompany_fiscalp',
        'partner_firstname',
        'partner_autocomplete',
        'l10n_it_pec',
        'fleet',
        'hr',
        'huroos_assvid_bondom',
        'sale_subscription',
        'documents',
        'crm',
        'assets_management',
        'huroos_assets_management',
        'huroos_ddt',
        'huroos_docfinance',
        'website_sale',
        'huroos_liquidazione_iva',
        'point_of_sale',
        'l10n_it_fiscal_document_type',
        'huroos_bilancio_competenza',
        'huroos_website_datepicker',
        'huroos_reports_ddt',
        'l10n_it_fatturapa_in',
        'account_invoice_start_end_dates',
        'date_range',
        'huroos_account_menu',
        'l10n_it_vat_statement_communication',
        'huroos_website_product_personalization',
        'huroos_schede_contabili',
        'l10n_it_withholding_tax',
        'huroos_nc_journal',
    ],

    'data': [
        'data/analytic_dimension.xml',
        'data/uom.xml',
        'data/data_week_days.xml',
        'data/data_quota.xml',
        'data/cron_manual.xml',
        'data/data_split_fatture.xml',
        'data/res_bank.xml',
        'data/data_product_product.xml',
        'data/document_folder_data.xml',
        'data/hr_employee.xml',
        'data/cron_apg_send_data.xml',
        'data/crm_lead_tag.xml',
        'data/ir_sequence.xml',
        'data/cron_sync_nso_youdox.xml',
        'data/invoice_it_template.xml',
        'data/cron_fix_description_website.xml',
        'data/affitto_line_type_data.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'wizard/affitto_deadline_creator.xml',
        'views/account_account.xml',
        'views/submenu.xml',
        'views/menu_root.xml',
        'views/apg_send_data.xml',
        'views/res_company.xml',
        'views/rette_viaggio.xml',
        'views/rette_presenza.xml',
        'views/rette_contratto.xml',
        'views/accolto_menu.xml',
        'views/rette_tariffa_gruppo.xml',
        'views/rette_tariffa.xml',
        'views/rette_quota.xml',
        'views/onlus_struttura.xml',
        'views/tag_structure.xml',
        'views/rette_contratto_tariffa.xml',
        'views/rette_contratto_tag.xml',
        'views/degree.xml',
        'views/res_partner.xml',
        'views/tag_gedi.xml',
        'views/uom_category.xml',
        'views/immobile_immobile.xml',
        'views/immobile_utenza.xml',
        'views/crm_lead.xml',
        'views/account_journal.xml',
        'views/account_move.xml',
        'views/fiscalposition.xml',
        'views/fleet_vehicle.xml',
        'views/product_template.xml',
        'views/hr_employee.xml',
        'views/sale_order.xml',
        'views/asset_asset.xml',
        'views/asset_category.xml',
        'views/invoice_period.xml',
        'views/assegno_vidimato.xml',
        'views/nso_order.xml',
        'views/mail_templates.xml',
        'views/nso_order_line.xml',
        'views/bonifico_domiciliato.xml',
        'views/res_users.xml',
        'views/website_sale_product_price.xml',
        'views/youdox_res_config_settings.xml',
        'views/account_vat_statement_view.xml',
        'views/fiscal_document_type.xml',
        'views/template.xml',
        'views/pos_config.xml',
        'views/pos_order.xml',
        'views/stock_warehouse.xml',
        'views/stock_picking.xml',
        'views/time_slot.xml',
        'views/website.xml',
        'views/website_sale.xml',
        'views/affitto.xml',
        'views/rel_journey_tariffa_line.xml',
        'views/huroos_ddt.xml',
        'views/account_move_send.xml',
        'views/account_move_line.xml',
        'views/product_pricelist.xml',
        'views/withholding_tax_move.xml',
        #'views/account_followup.xml',
        'wizard/wizard_import_account.xml',
        'wizard/wizard_active_account.xml',
        'wizard/wizard_create_invoice.xml',
        'wizard/wizard_change_invoicedate.xml',
        'wizard/wizard_import_nso.xml',
        'wizard/wizard_import_fatturapa.xml',
        'wizard/wizard_import_contacts.xml',
        'wizard/wizard_giroconto_vat.xml',
        'wizard/wizard_change_invoicedate.xml',
        'wizard/wizard_adegua_tariffa.xml',
        'wizard/wizard_create_packages.xml',
        'wizard/account_payment_register.xml',
        'wizard/huroos_delivery_note_invoice.xml',
        'wizard/huroos_schede_contabili_wizard.xml',
        'wizard/wizard_import_assets.xml',
        'report/product_label_layout.xml',
        'report/report_vat_statement.xml',
        'wizard/wizard_storno_confirmation.xml',
        'report/invoice_template.xml',
        'report/huroos_report_ddt.xml',
        'views/fatturapa_attachment_in.xml',
        'views/res_config_settings.xml',
        'views/journal_zero_price.xml',
        'report/bollettino_invoice.xml',
        'report/huroos_schede_contabili_template.xml',
        'data/invoice_it.xml'
    ],
    'assets': {
        'web.assets_frontend': [
            'huroos_apg23/static/src/js/variant_mixin.js',
            'huroos_apg23/static/src/js/time_slot_checkout.js',
            'huroos_apg23/static/src/js/delivery_date.js',

        ],
        'web.assets_backend': [
            'huroos_apg23/static/src/js/button_invoice_presence.js',
            'huroos_apg23/static/src/js/lazy_barcode_cache.js',
            'huroos_apg23/static/src/xml/button_invoice_presence.xml',
            'huroos_apg23/static/src/xml/SwitchCompanyMenu.xml',
            'huroos_apg23/static/src/xml/SwitchCompanyMenu.js',
            'huroos_apg23/static/src/xml/SwitchCompanyItem.xml',
            'huroos_apg23/static/src/scss/styles.scss',
        ],

        'point_of_sale._assets_pos': [
            'huroos_apg23/static/src/js/point_of_sale.js',
        ],
    }
}
